name: gsamuels
favicon: null
layout_spectrum: 0.08436680352315307
typography_spectrum: 0.23547
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f7ce6b'
    - '#967f7f'
    - '#261a1e'
    - '#5b4b4c'
    - '#a2a5b1'
  brandStrength: 0.25
  lightness: 0.6743022291921079
  saturation: 0.44673660956323147
  rhythmicContrast: 0.25
purpose: []
