name: gsamuels
favicon: null
layout_spectrum: 0.5
typography_spectrum: 0.50295
title: George Siosi Samuels
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fed966'
    - '#0086be'
    - '#5e9d8b'
    - '#fffff3'
    - '#a1c89f'
  brandStrength: 0.5
  lightness: 0.6875
  saturation: 0.8125
  rhythmicContrast: 1
purpose: []
