name: gsamuels
favicon: null
layout_spectrum: 0
typography_spectrum: 0.23547
title: George Siosi Samuels
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fed966'
    - '#0086be'
    - '#5e9d8b'
    - '#fffff3'
    - '#a1c89f'
  brandStrength: 0.25
  lightness: 0.6743022291921079
  saturation: 0.25
  rhythmicContrast: 0.25
purpose: []
